scalekit-inc/developer-docs

package.json, pnpm-lock.yaml
- Upgraded "@astrojs/react" from ^4.2.7 to ^4.3.0
- Upgraded "@astrojs/vue" from ^5.0.13 to ^5.1.0
- Upgraded "astro" from ^5.7.13 to ^5.8.0
- Updated pnpm-lock.yaml to reflect the new dependency versions and ensure consistency across the project.
=> Update dependencies in package.json and pnpm-lock.yaml

src/components/ScalarReference.vue, src/styles/api-reference.css
- Updated the ScalarReference component to include a logo link and improved navigation links.
- Removed inline styles and added a new CSS file for better organization of styles.
- Introduced a comprehensive stylesheet for consistent theming and layout across the API reference.
=> Refactor ScalarReference component and add new styles

src/content/docs/index.mdx
- Specifically applies styles ONLY to home index page alone
- Invites the reader to content at the earliest
- [See the preview](https://preview-home-page--scalekit-starlight.netlify.app/)
=> The home page is more wider and invites to content earlier

public/api/scalekit.swagger.json
=> API reference documentation for passwordless auth

src/content/docs/guides/idtoken-claims.mdx, src/content/docs/guides/sso/idp-init-sso.mdx, src/content/docs/index.mdx
This PR attempts to identify the specific and quick-win areas where user feedback can be incorporated to improve the content in the docs.
=> Direct feedback from users

src/content/docs/guides/integrations/auth-systems/firebase.mdx
=> Include options to use Firebase with Scalekit

src/content/docs/guides/integrations/scim-integrations/okta-scim.mdx
The visiblity of this note needs to be improvised. Hence updating it to get it better attention.
=> Change note to caution

src/content/docs/fsa/quickstart.mdx
=> Add Java Snippets quickstart.mdx

src/content/docs/fsa/guides/organization-switching.mdx
Since new approach are introduced to control organization switching, this PR documents to the organization switching documentation
=> Adds manual methods the organization switcher page

src/content/docs/fsa/guides/organization-switching.mdx
=> Improve organization switcher docs for clarity

public/api/scalekit.swagger.json, public/api/scalekit.swagger.json.bak.2025-07-22T11-57-21-511Z
- Reformatted the Swagger JSON structure for better clarity, including consistent indentation and line breaks.
- Updated tags for various API endpoints to use array format for consistency.
- Enhanced existing endpoint descriptions and examples for better understanding.
- Updated enumerations in definitions for better clarity and completeness.
- Removed deprecated sections and ensured all definitions are up-to-date.
- Deleted the backup file of the previous Swagger JSON.
=> Fixed a bug with roles object in create new user API

src/components/ScalarReference.vue
- Updated the color mode update function to check for system preferences when no saved color mode is found in localStorage.
- Improved logic to determine the appropriate color mode based on user settings and system theme.
=> Enhance color mode handling in ScalarReference component

package.json, pnpm-lock.yaml
This adds a easier view into[ additional resource links](https://preview-update-api-scalar--scalekit-starlight.netlify.app/apis/).
=> Upgrading the API reference Scalar component

astro.config.mjs, package.json, pnpm-lock.yaml, src/content.config.ts, src/content/docs/reference/webhooks/directory-events.mdx, src/content/docs/reference/webhooks/event-object.mdx
=> Left align content and bring customizability to "overview" in ToC

src/components/overrides/PageSidebar.astro
As part of our ongoing focus on usability, this change realigns sidebar actions like Edit and "Copy LLM Context" so they appear consistent and intuitive. Customers will now be able to quickly find and use these tools without unnecessary visual clutter.
=> Align the ToC and sidebar actions

src/content/docs/sso/guides/idp-init-sso.mdx
This change does not have a preview link, please use the changed files tab to review and approve.
=> Improves by adding new context about initial login endpoints

src/content/docs/fsa/quickstart.mdx
[Preview this change](https://preview-fsa-video--scalekit-starlight.netlify.app/)
- Import VideoPlayer component from starlight-videos/components
- Add explanatory video above the authentication flow diagram
- Enhance user understanding with visual demonstration
=> feat: add video player to FSA quickstart page

src/components/templates/_sso-integrations.mdx, src/content/docs/guides/integrations/sso-integrations/generic-oidc.mdx, src/content/docs/guides/integrations/sso-integrations/generic-saml.mdx, src/content/docs/guides/integrations/sso-integrations/shibboleth-saml.mdx
[View the preview](https://preview-shibboleth--scalekit-starlight.netlify.app/guides/integrations/sso-integrations/shibboleth-saml/)
=> v0 draft: Add Shibboleth IdP Integration Guide

public/api/scalekit.swagger.json, public/api/scalekit.swagger.json.bak.2025-09-03T02-48-48-954Z, src/content/docs/fsa/guides/allowed-email-domains.mdx
[Preview the changes](https://preview-snippets-domains--scalekit-starlight.netlify.app/)
- Reformatted JSON arrays to multi-line for better clarity.
- Updated tags and descriptions for consistent terminology across the API specification.
- Enhanced the organization of tags and definitions, ensuring enums are uniformly formatted.
- Added code samples for various SDKs to demonstrate API usage effectively.
- Improved overall maintainability and clarity of the API documentation.
=> Domains related Nodejs code snippets

src/content/docs/apis/index.mdx
- Added a preload link for the Swagger JSON file to improve loading performance.
- Changed the ScalarReference component from `client:only` to `client:visible` for better rendering behavior in the API documentation.
=> Improves the page loading speed for API reference

src/styles/custom.css
…and enhancing line-height consistency
- Removed deprecated typography tokens to simplify the CSS structure.
- Added consistent line-height settings for html and body elements to improve readability site-wide.
=> Hotfix: line height bug reintroduced due to merges - fixed

src/content/docs/agent-actions/quickstart.mdx, src/content/docs/dev-kit/code-samples.mdx
- Fix code examples to point to newly created sample apps.
- Minor fixes in sample code for quick start
=> fix code samples
